### ISSUE TITLE
Investigating elevated 500 errors for project management APIs of a tiny subset (1-2 projects)

### ISSUE THREAD

**Issue by aeneasr** [ory/status#116]
We are investigating elevated 500 errors affecting a tiny (1-2) subset of Ory Cloud Projects. The problem prevents customers from accessing the Ory Console to manage the affected projects. We already identified a potential cause for the issue and are working on a fix.

**Comment by aeneasr** [comment]
We are continuing the investigation and have identified the root cause of the issue. We are working on a fix.

**Comment by tricky42** [comment]
You can find a detailed report here: https://www.ory.sh/post-mortem-2022-08-11/
